export const POEMS = [
  { id: "schweif", title: "Schweif", lang: "German", date: "October 26, 2022", lines: ["Sch Weif","Sc we if","Wir laufen zusammen auf einem Schweif","Hand in Hand; ich f\u00fchle deine ist k\u00fchl gegen meine sichere Hand.","Die D\u00e4mmerung wird lichter","Die Luft ist licht und leicht:","Niemand kann uns halten.","Niemand kann uns halten?","Die Sonne und die Hitze steigen auf w\u00e4hrend unsere Stimmungen","Tiefer im schlammigen Schweif als unsere Fu\u00dfspuren versinken.","Der Schweif wird l\u00e4nger wir mehr und mehr von uns trennen.","Schwei\u00dfperlen formen auf meinen Lippen,","Aber ich versch\u00e4rfe meinen Griff auf einer Handfl\u00e4che","Und stampfte vorw\u00e4rts.","Die Abendsonne ist in unseren Augen,","aber wir seen beide die Stra\u00dfengabelung.","Wir verstecken unsere st\u00e4ndigen Tr\u00e4nen","So und sehen, dass es Zeit sich zu trennen ist.","Du k\u00fcsst meine Hand","Ich trockne deine Wange","Und wir laufen allein,","H\u00e4nde leer und schweifen vereinsamt"] },
  { id: "onopgelos", title: "onopgelos", lang: "Afrikaans", date: "May 23, 2023", lines: ["Die woorde wat uit my mond vloei voel","sag en soet,","soos 'n beskuit wat te lank","in die koffie gedompel is.","Daar sit te veel gevoelens aan die onderkant","van die beker,","versteek","daar onder die ryk bruin drank.","Ek warrel die onopgeloste suiker korrels","onnadenkend","met 'n haatdraende tong."] },
  { id: "comfortably-numb", title: "comfortably numb", lang: "English", date: "December 8, 2022", lines: ["waves shrink in their haste to the shore,","reducing to a thin sheet of ice over my feet.","tendrils of kelp wrap around my ankles,","soft and steady against the current \u2013","I swirl them around with a pointed foot","and marvel at the orange glow of the sunset","reflecting upon the ripples my chass\u00e9s create.","wind plays roughly with my hair,","tossing and turning with each pirouette;","water crashes against my legs, my stomach,","my arms until I am numb against the Atlantic chill.","","  your jersey clings to my chest,","  soaked in salt water and stretched","  out past its years of acception."] },
  { id: "saunders", title: "Saunders", lang: "English", date: "July 11, 2023", lines: ["Eyes green as seafoam;","twinkles glint at the corner","of her eyes and pupils roam","to the waves where gulls saunter.","Laugh gentle as wind chimes,","swaying in the ocean breeze;","the joy that escapes stops time","and puts friends at ease.","Presence warm as the summer sun;","chatter flows with the joy","of a life shared with precious ones,","floating like the far out buoys."] },
  { id: "soda-pop-smile", title: "soda pop smile", lang: "English", date: "March 13, 2023", lines: ["your smile cracks open with the same","excitement as a can of soda \u2013","bubbles rushing to the surface and","scents of sparkles tickling my face.","sweet as the sugar and rich as the colour,","caramel dreams of laugh lines and summer."] },
  { id: "scent-of-summer", title: "scent of summer", lang: "English", date: "February 27, 2023", lines: ["when it pelts down with rain","it is the growth that I adore;","exposed roots muddied","with life of petrichor.","baby leaves shudder with","every drop upon its fall,","and petals flutter in the wind","like a butterfly's wings in its stall.","rays of icy yellow peek past","the clouds with curious sneak,","eyeing the steaming tarmac","enjoying repose after a week's heat.","tendrils of green will soon","unfurl from stems yet bare \u2013","gleaning waxy spines to absorb","the last of the summer season's fair."] },
  { id: "do-your-mornings", title: "do your mornings hurt like this too?", lang: "English", date: "March 8, 2023", lines: ["my pink mug still stained","from yesterday's coffee","inside the ring and run down the","side in dried drips.","sat on my bedside table","surrounded by earrings, candles,","the hope that the morning","brought before I left for work.","Rosie follows me to the kitchen","with a shivering tail","chirping with delight that I'm","awake after her hours' play outside.","I pour the boiling water over","the instant coffee with too much","sleep still in my eyes.","the aroma tickles my face","with hints of yesteryear's dreams.","this mug with the chip inside","that my sponge gets caught on","every time I wash it as if a regular","reminder that I haven't yet replied","to your messages."] },
  { id: "geen-bui", title: "geen bui vir 'n spie\u00ebl nie", lang: "Afrikaans", date: "January 15, 2023", lines: ["Ek sit in my klein kar","en hoor 'n sanger sing sag","op die radio.","Sy sing van 'n gebroke hart,","met trane wat van haar o\u00eb","oor 'n onbeantwoorde liefde","swaar val.","Haar stem word vir my te veel","en ek sit haar beslis af."] },
  { id: "misbruik", title: "misbruik", lang: "Afrikaans", date: "December 15, 2022", lines: ["ek't geen meer totsiense nie \u2013","jy't die laaste een vandag gegryp.","Maar jy weet dit steeds nie.","Natuurlik gaan ek jou mis \u2013","jy't my geleer lees","maar nie hoe om myself te lief nie.","Huil jy oor my","in jou kar op pad huis toe","soos ek saans doen?","My kop mis die inkeping","van jou bors waar dit nesgemaak het","toe ek jou gedruk het.","Maar ek sal nooit die harde","woorde mis wat jy na my geslinger het","toe jy te veel gedrink het nie."] },
  { id: "verdrink", title: "verdrink", lang: "Afrikaans", date: "October 26, 2022", lines: ["Hoe meer ek dink,","hoe meer ek val","onder n oppervlak","van die see; verdrink","my drome sukkel om die","son te sien as die stemme","gooi","soos 'n ongewenste stompie.","Die doelwitte l\u00ea in my bed","en bly daar as ek uit die deur","stap verveeld en moeg","van pogings om my te red.","Ek sit my brein af,","dra my kop hoog","En hoop dat die swart hond","nie so hard blaf."] },
  { id: "beschutzt", title: "besch\u00fctzt", lang: "German", date: "November 22, 2023", lines: ["Die Waldeinsamkeit","meiner Jugend ein Asyl;","du hast mich besch\u00fctzt."] },
];

export const WRITING = [
  { id: "so-long", title: "\u201cSo long, and thanks for all the fish\u201d", date: "December 22, 2023", category: "Longer rambling", paragraphs: ["The past week has brought up many fond memories while packing up to move; as I took down my wall of photos I couldn\u2019t help but cringe at my pixie cut phase and marvel at how much my friends and I have grown.","I sat for hours on my floor as I pulled books off my shelves, stopping to remember who I was when I read them. I discovered Bryce Courtenay\u2019s Peekay on a rainy day after school, learned the importance of a towel in intergalactic travel from Douglas Adams while preparing for dance class, and teared up in bed at the melancholy of sunsets with Antoine de Saint-Exup\u00e9ry well past bedtime. The moments captured in those photos and the lessons learned in a myriad of chapters have shaped me into the person I am today.","How do we start new chapters, without making those iterations of ourselves feel like they\u2019ve been left behind?","I suppose we can start by saying \u2018thank you\u2019 \u2013 to the version that learned the hard way mom was right (you will regret not bringing your jersey), the one who discovered the importance of a glass of water after a night drinking (painful), and the one who got to deal with heartbreak for the first time (taking one for the team).","Whether we realise it or not, we honour our younger selves, their values, and their experiences every day. From those inside jokes we have with ourselves that make us giggle, to the people with whom we surround ourselves and the careers we choose to pursue \u2013 we need not worry about them being left behind.","Growth isn\u2019t abandoning the past. Each version of ourselves contributes to the unique tapestries of our identities. And every thread carries importance. No matter how many chapters we navigate in our lives, our true essences will always remain \u2013 a testament to the beauty of embracing the unknown."] },
  { id: "five-six-seven-eight", title: "Five-six-seven-eight", date: "2024", category: "Creative non-fiction", paragraphs: ["I was driving home the other day, stuck in after-school traffic on Campground Road. On the pavement a few metres away, three girls were hand in hand skipping \u2013 two whose backpacks were almost bigger than they were. After a few hops, they let go each others hands. The little ones started leaping, enveloped by the golden afternoon sun as the older girl watched on.","I was catapulted into a memory. I was five years old and barefoot in a leotard at the dance studio. It was a hot Wednesday afternoon, and we were practicing leaping. Half the girls were sitting cross-legged in front of a whirring fan (working overtime) in the front corner of the room. The rest of us stood at the back corner in a line.","Auntie Carol had stuck two parallel lines of masking tape on the polished wooden floor to create a \u201criver\u201d, and placed a plastic toy crocodile inbetween. We were to pas de Bourr\u00e9e toward the river, and leap over it so as not to get bitten by the crocodile. Auntie Carol counted out five, six, seven-eight over \u201cPush The Button\u201d by Sugababes, with eight being our cue to go.","The two girls in front of me made it over the river and joined the girls at the fan. It was time to face the crocodile. The tape transformed into river banks and the crocodile flashed its sharp teeth and swished its tail. My tummy twisted. Was I scared of getting bitten by this scaly beast or just worried I\u2019d fumble in front of my peers?","Point your toes, keep your arms gently rounded, don\u2019t grimace. My right foot made it across, and my left foot followed. My feet certainly hadn\u2019t stayed pointed, and my arms had flailed around with minds of their own. But I\u2019d made it. \u201cGood girl!\u201d Auntie Carol sang.","I couldn\u2019t help but smile at how much I\u2019d enjoyed the journey, even if I\u2019d looked clumsy doing it. Next time you\u2019re anxious to try something new, you might not get it perfect the first time. But it\u2019s only when you\u2019ve made that first leap of faith that you teach yourself it\u2019s less daunting than you think. All you need is some Sugababes and a little momentum."] },
  { id: "peanut-butter", title: "Peanut Butter", date: "2026", category: "Creative non-fiction", paragraphs: ["No matter if I wake up in a rooftop tent or in bed next to my cat, my quiet (read: quiet) early morning ritual always includes three components:\n1. Brushed teeth\n2. Coffee\n3. Sudoku","The other morning, an uninvited fourth component announced itself loudly: an obnoxious craving for peanut butter cookies \u2013 the rich, buttery kind my mom baked on a Sunday evening.","They\u2019re delicious. But also incredibly messy to make. No matter how careful you are, flour goes everywhere and it\u2019s so much cleanup. The thought of such a mess gave me hives.","My morning ritual came to an end. The craving didn\u2019t. I caved. Two kilograms of Yum Yum crunchy peanut butter came home with me after work that evening (smooth peanut butter is for masochists).","Oven: preheated. The trays (and my lungs): doused with Spray \u2019n Cook. Electric mixer: locked and loaded.","The creamed butter and sugar went flying. The flour floated gently to the floor. And while rolling the balls, my hands were so covered in dough that I was at risk of a cannibalistic attack from the Cookie Monster.","By the time the last tray came out of the oven, the kitchen was a wreck. But the cleanup didn\u2019t even last a full podcast episode of Trixie and Katya. There\u2019s something almost offensive about how small the mess actually was compared to the anxiety I\u2019d built around it.","While munching on my second cookie, I wanted to understand why I had the craving in the first place. Great as the cookies are, what satiated my hunger was the haphazard, sticky process of making something. I was craving permission \u2013 permission to spill flour, to mismeasure, to not know exactly how it would turn out.","\u201cDisciplined\u201d, \u201cperfectionist\u201d, and \u201cstructured\u201d all look great on a CV. But it\u2019s a rigid mindset that feeds my inner critic; it tells me that making mistakes and nonlinear progress are shameful. It confuses precision with self-worth. It forgets that most good things are iterative.","Baking allowed me the freedom to make something imperfect and let that be enough.","Not everything worth building arrives fully formed. Sometimes the work is simply staying in the kitchen long enough to make a mess \u2013 and not apologise for it."] },
];

export const SERVICES_DATA = [
  { icon: "landingPage", name: "Landing Pages", desc: "High-conversion pages structured from identity resonance to application." },
  { icon: "social", name: "Social Media", desc: "Organic and paid campaigns rooted in audience psychology." },
  { icon: "email", name: "Email Campaigns", desc: "Structured storytelling arcs that deepen emotional buy-in." },
  { icon: "resource", name: "Resource Development", desc: "Educational toolkits, guides, and lead magnets designed with care." },
];

export const TOOLKITS = [
  { name: "Endometriosis Toolkit", desc: "An educational resource for newly-diagnosed women. It explains the condition in a digestible way and offers practical tools for communicating needs in personal and professional life. Includes an intro to endo, how to explain pain, boundary-setting scripts, symptom-friendly foods, flare-up reminders, and tea recommendations.", color: "#C47BA0", cover: "/endo-cover.png", link: "https://drive.google.com/file/d/1bT0paFuXWwSxsy5ppjTWjurtipmsWxgS/view?usp=drive_link" },
  { name: "Lupus Toolkit", desc: "A compassionate guide for those navigating lupus. Covers signs and symptoms, medication types, a body map of affected systems, medical gaslighting and self-advocacy, a printable symptom tracker, workplace disclosure templates, flare-up essentials, and curated resources.", color: "#7B8FC4", cover: "/lupus-cover.png", link: "https://drive.google.com/file/d/1tkFSVT4cYL-mzrLnh3qa2gA25KjUvpUL/view?usp=sharing" },
];

export const CASES = [
  { title: "Dyslexic Mastermind", type: "Landing Page & Email Funnel", result: "\u00a35,000+ in revenue from marketing strategy conversions", link: "https://www.dyslexia-in-adults.com/dyslexia-mastermind", desc: "Wrote and designed the landing page and full funnel architecture for Dyslexic Mastermind, a premium group coaching programme for dyslexic professionals. Designed the high-conversion landing page, developed the complete marketing email sequence using a structured storytelling arc, and aligned webinar messaging, sales positioning, and application flow into a cohesive conversion journey." },
  { title: "Connections In Mind", type: "End-to-End Marketing & Client Operations", result: "Up to 24 signups per cohort at \u00a3790+ per person", link: "https://cim-brainhub.com/coach-training-courses/", desc: "Managed the entire marketing funnel for Connections In Mind\u2019s Executive Function Coach Training programmes every quarter, handling three seasonal cohorts. This included email and social media promotion, client communications, sales pipeline management on Insightly CRM, and handover to course coordinators upon payment. Also collaborated on the course handbook each quarter." },
  { title: "AUDHD Instagram Campaign", type: "Social Media Content", result: "High-engagement carousel reaching non-follower audiences", link: "https://www.instagram.com/p/DFde9SWCHEZ/", desc: "Created an educational Instagram carousel for Connections In Mind exploring AUDHD (the co-occurrence of autism and ADHD), making neuroscience research accessible for a broad audience of neurodivergent adults and parents of neurodivergent children." },
];

export const BOOKING_URL = "https://calendar.app.google/hDrsCpixdVSpDzsa6";
export const EMAIL = "meganannewright16@gmail.com";
